name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            for f in $(find . -name 'samenvatting.tex'); do
              directory=$(dirname "$f");
              echo $directory;
              latexmk -pdf -shell-escape -interaction=nonstopmode -halt-on-error -cd $f; 
            done
