name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          run: |
            for d in */*/ ; do
              latexmk -pdf -shell-escape -interaction=nonstopmode -halt-on-error -cd ${d}samenvatting.tex
            done
