name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)"
      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            for f in $(echo ${{ steps.getfile.outputs.files }} | grep -i '*.tex'); do
              latexmk -pdf -shell-escape -interaction=nonstopmode -halt-on-error -cd $f; 
            done;
      - name: Commit files
        run: |
          git config --local user.email "vanhouttetuur@gmail.com"
          git config --local user.name "zjeffer"
          git commit -am "Upload pdf files"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
